"""One-time generator: picks 4 random observable pairs (seed=42), creates
per-pair notebooks (noise models only, all 35 params, no focus params) and a
master runner script. Re-run to regenerate.

Each pair trains 7 cases (5 mixed-noise + 2 single-observable references) —
see _default_noise_cases in _pair_pipeline.py. Results (R2 matrices, CSVs,
heatmaps, results.pt) cover all 35 parameters; pick plots by hand afterward
with analyze.py / analyze_all.py.

Usage:  cd sweep && python3 generate_sweep.py
"""
import os
import sys
from itertools import combinations
import numpy as np

# All 14 observables in the HDF5 (from data_L50_TNG_v3.hdf5)
OBSERVABLES = [
    "MBH_Mh_s61", "MBH_Mh_s90",
    "Mg_Mh_s61",  "Mg_Mh_s90",
    "Ms_Mh_s61",  "Ms_Mh_s90",
    "Rs_Ms_s61",  "Rs_Ms_s90",
    "SFR_Ms_s61", "SFR_Ms_s90",
    "SFRH", "SFRH_100Myr",
    "Zs_Ms_s61",  "Zs_Ms_s90",
]

N_PAIRS = 4                 # 4 random observable pairs, noise-models-only sweep
SEED = 42
EPOCHS = 1500              # per-case F* training epochs

HERE = os.path.dirname(os.path.abspath(__file__))

# ---------------------------------------------------------------------------
# Pick pairs
# ---------------------------------------------------------------------------
all_pairs = list(combinations(OBSERVABLES, 2))
rng = np.random.default_rng(SEED)
idx = rng.choice(len(all_pairs), size=N_PAIRS, replace=False)
picked = [all_pairs[i] for i in idx]
print(f"Picked {N_PAIRS} pairs (seed={SEED}):")
for i, (a, b) in enumerate(picked, 1):
    print(f"  {i}. {a}  ×  {b}")


def _dirname(i, a, b):
    return f"pair_{i:02d}_{a}__{b}"


# ---------------------------------------------------------------------------
# Per-pair notebook template — imports the shared pipeline and calls run_pair
# ---------------------------------------------------------------------------
PAIR_NB_TEMPLATE = '''# ---
# jupyter:
#   jupytext:
#     formats: ipynb,py:percent
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: "1.3"
#   kernelspec:
#     display_name: py311-main
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Sweep pair {i:02d}: {obs_a} × {obs_b}
#
# Auto-generated by generate_sweep.py (seed={seed}). Runs the noise-model-only
# pipeline (7 cases: 5 mixed + 2 single-observable, {epochs} epochs each,
# all 35 parameters, no focus params) for this observable pair, saves R2
# heatmaps + a torch.save results.pt in ./results/.
#
# Regenerate all pair notebooks with:  cd .. && python3 generate_sweep.py

# %%
import sys, os
_HERE = os.path.dirname(os.path.abspath(__file__)) if "__file__" in globals() else os.getcwd()
sys.path.insert(0, os.path.dirname(_HERE))  # sweep/
from _pair_pipeline import run_pair

# %%
run_pair(
    obs_a="{obs_a}",
    obs_b="{obs_b}",
    out_dir=os.path.join(_HERE, "results"),
    epochs={epochs},
)
'''

# ---------------------------------------------------------------------------
# Master runner shell script
# ---------------------------------------------------------------------------
RUN_ALL_TEMPLATE = """#!/usr/bin/env bash
# Sequential runner — auto-generated by generate_sweep.py
# Runs each pair notebook (noise models only). Any failure logs and continues.

set -u
cd "$(dirname "$0")"
mkdir -p logs
LOG_INDEX=logs/index.log
PYTHON={python}

echo "=== sweep started $(date -u +%Y-%m-%dT%H:%M:%SZ) ===" | tee -a "$LOG_INDEX"

run_one() {{
    local label="$1"; local script="$2"; local log="$3"
    echo "--- [$label] $(date -u +%H:%M:%S) START  $script ---" | tee -a "$LOG_INDEX"
    if "$PYTHON" "$script" > "$log" 2>&1; then
        echo "--- [$label] $(date -u +%H:%M:%S) OK ---" | tee -a "$LOG_INDEX"
    else
        rc=$?
        echo "--- [$label] $(date -u +%H:%M:%S) FAIL rc=$rc  see $log ---" | tee -a "$LOG_INDEX"
    fi
}}

{pair_calls}

echo "=== sweep finished $(date -u +%Y-%m-%dT%H:%M:%SZ) ===" | tee -a "$LOG_INDEX"
"""

# ---------------------------------------------------------------------------
# Write everything
# ---------------------------------------------------------------------------
pair_calls = []
for i, (a, b) in enumerate(picked, 1):
    dname = _dirname(i, a, b)
    ddir = os.path.join(HERE, dname)
    os.makedirs(ddir, exist_ok=True)
    nb_py = os.path.join(ddir, "run.py")
    with open(nb_py, "w") as f:
        f.write(PAIR_NB_TEMPLATE.format(i=i, obs_a=a, obs_b=b, epochs=EPOCHS, seed=SEED))
    print(f"  wrote {nb_py}")
    pair_calls.append(
        f'run_one "pair_{i:02d}" "{dname}/run.py" "logs/pair_{i:02d}.log"'
    )

runner = os.path.join(HERE, "run_all.sh")
with open(runner, "w") as f:
    f.write(RUN_ALL_TEMPLATE.format(
        python="/Users/nicolasgarcia/opt/anaconda3/envs/py311-main/bin/python3",
        pair_calls="\n".join(pair_calls),
    ))
os.chmod(runner, 0o755)
print(f"  wrote {runner}")

# Sync jupytext pairs so .ipynb are runnable/openable too (best-effort)
try:
    import subprocess
    for i, (a, b) in enumerate(picked, 1):
        p = os.path.join(HERE, _dirname(i, a, b), "run.py")
        subprocess.run(["/Users/nicolasgarcia/opt/anaconda3/envs/py311-main/bin/python3",
                        "-m", "jupytext", "--set-formats", "ipynb,py:percent", p],
                       check=False, capture_output=True)
except Exception as e:
    print(f"  [warn] jupytext sync skipped: {e}")

print("\nDone. To launch:")
print(f"  bash {runner}    (foreground)")
print(f"  nohup bash {runner} > /dev/null 2>&1 &   (background)")
