#!/usr/bin/env bash
# Sequential runner — auto-generated by generate_sweep.py
# Runs each pair notebook (noise models only). Any failure logs and continues.

set -u
cd "$(dirname "$0")"
mkdir -p logs
LOG_INDEX=logs/index.log
PYTHON=/Users/nicolasgarcia/opt/anaconda3/envs/py311-main/bin/python3

echo "=== sweep started $(date -u +%Y-%m-%dT%H:%M:%SZ) ===" | tee -a "$LOG_INDEX"

run_one() {
    local label="$1"; local script="$2"; local log="$3"
    echo "--- [$label] $(date -u +%H:%M:%S) START  $script ---" | tee -a "$LOG_INDEX"
    if "$PYTHON" "$script" > "$log" 2>&1; then
        echo "--- [$label] $(date -u +%H:%M:%S) OK ---" | tee -a "$LOG_INDEX"
    else
        rc=$?
        echo "--- [$label] $(date -u +%H:%M:%S) FAIL rc=$rc  see $log ---" | tee -a "$LOG_INDEX"
    fi
}

run_one "pair_01" "pair_01_Mg_Mh_s90__Rs_Ms_s90/run.py" "logs/pair_01.log"
run_one "pair_02" "pair_02_MBH_Mh_s61__SFR_Ms_s61/run.py" "logs/pair_02.log"
run_one "pair_03" "pair_03_Ms_Mh_s90__SFR_Ms_s90/run.py" "logs/pair_03.log"
run_one "pair_04" "pair_04_Rs_Ms_s61__Zs_Ms_s61/run.py" "logs/pair_04.log"

echo "=== sweep finished $(date -u +%Y-%m-%dT%H:%M:%SZ) ===" | tee -a "$LOG_INDEX"
