# ---
# jupyter:
#   jupytext:
#     formats: ipynb,py:percent
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.19.4
#   kernelspec:
#     display_name: py311-main
#     language: python
#     name: py311-main
# ---

# %% [markdown]
# # Comprehensive analysis -- MBH_Mh_s90 x Rs_Ms_s61
#
# Materialized from analyze.py for this pair specifically (see that file for
# the shared, PAIR_IDX-driven version, and for cross-pair comparison).
#
# **Flow** (top-to-bottom, edit as you go):
# 1. Load this pair
# 2. Heatmaps (aligned R2, shuffled R2, delta R2)
# 3. Suggest & set FOCUS_PARAMS
# 4. Per-parameter mean-net plots: predictions, dual curve, attractor map, unordered-pair normalized, pair-normalized, shuffle scatter, pair-truth scatter
# 5. Moment-network plots (only render if this pair has a moment head)
# 6. Save any current figure
# 7. Scratch cell -- every function in src/plots.py is available as ctx.plots.<name>
#
# Auto-generated by generate_analysis_notebook.py.

# %%
# %matplotlib inline
import sys, os, importlib
_HERE = os.path.dirname(os.path.abspath(__file__)) if "__file__" in globals() else os.getcwd()
_SWEEP = os.path.dirname(_HERE)
if _SWEEP not in sys.path:
    sys.path.insert(0, _SWEEP)

import _analyze_helpers
importlib.reload(_analyze_helpers)
from _analyze_helpers import load_pair, relabel_figure, label_cases, suggest_params, build_dual_r2_df
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

# %% [markdown]
# ## 1. Load this pair

# %%
ctx = load_pair(pair_dir="pair_07_MBH_Mh_s90__Rs_Ms_s61")
ctx.summary()

# %% [markdown]
# ## 2. Heatmaps

# %% [markdown]
# ### 2a. Aligned R2

# %%
labels = label_cases(ctx, ctx.cases)
df = pd.DataFrame(ctx.r2_matrix, index=labels, columns=ctx.param_names)
plt.figure(figsize=(16, 5))
sns.heatmap(df, vmin=-1, vmax=1, annot=True, fmt=".2f", cmap="Spectral",
            linewidths=0.2, cbar_kws={"label": "aligned R2"})
plt.title(f"Aligned R2  |  {ctx.obs1}  x  {ctx.obs2}")
plt.tight_layout(); plt.show()

# %% [markdown]
# ### 2b. Shuffled R2 -- obs2 shuffled (survives only if model reads obs1)

# %%
if ctx.r2_matrix_shifted_obs is not None:
    df = pd.DataFrame(ctx.r2_matrix_shifted_obs, index=labels, columns=ctx.param_names)
    plt.figure(figsize=(16, 5))
    sns.heatmap(df, vmin=-1, vmax=1, annot=True, fmt=".2f", cmap="Spectral",
                linewidths=0.2, cbar_kws={"label": "R2 (obs2 shuffled)"})
    plt.title(f"obs2 shuffled  |  {ctx.obs1}  x  {ctx.obs2}")
    plt.tight_layout(); plt.show()

# %% [markdown]
# ### 2c. Shuffled R2 -- obs1 shuffled

# %%
if ctx.r2_matrix_shifted_both is not None:
    df = pd.DataFrame(ctx.r2_matrix_shifted_both, index=labels, columns=ctx.param_names)
    plt.figure(figsize=(16, 5))
    sns.heatmap(df, vmin=-1, vmax=1, annot=True, fmt=".2f", cmap="Spectral",
                linewidths=0.2, cbar_kws={"label": "R2 (obs1 shuffled)"})
    plt.title(f"obs1 shuffled  |  {ctx.obs1}  x  {ctx.obs2}")
    plt.tight_layout(); plt.show()

# %% [markdown]
# ### 2d. Delta R2 -- obs2 shuffled (negative = information lost)

# %%
if ctx.r2_matrix_shifted_obs is not None:
    delta = ctx.r2_matrix_shifted_obs - ctx.r2_matrix
    df = pd.DataFrame(delta, index=labels, columns=ctx.param_names)
    plt.figure(figsize=(16, 5))
    sns.heatmap(df, center=0.0, vmin=-0.5, annot=True, fmt=".2f", cmap="Spectral",
                linewidths=0.3, cbar_kws={"label": "delta R2 (obs2 shuffled)"})
    plt.title(f"delta R2 -- obs2 shuffled  |  {ctx.obs1}  x  {ctx.obs2}")
    plt.tight_layout(); plt.show()

# %% [markdown]
# ### 2e. Delta R2 -- obs1 shuffled

# %%
if ctx.r2_matrix_shifted_both is not None:
    delta = ctx.r2_matrix_shifted_both - ctx.r2_matrix
    df = pd.DataFrame(delta, index=labels, columns=ctx.param_names)
    plt.figure(figsize=(16, 5))
    sns.heatmap(df, center=0.0, vmin=-0.5, annot=True, fmt=".2f", cmap="Spectral",
                linewidths=0.3, cbar_kws={"label": "delta R2 (obs1 shuffled)"})
    plt.title(f"delta R2 -- obs1 shuffled  |  {ctx.obs1}  x  {ctx.obs2}")
    plt.tight_layout(); plt.show()

# %% [markdown]
# ## 3. Suggest parameters -> set `FOCUS_PARAMS`

# %%
suggestions = suggest_params(ctx, top_n=8, min_aligned_r2=0.1)

# %%
FOCUS_PARAMS = suggestions["union"]        # or e.g. ["θ4", "θ7", "θ11"]
print(f"FOCUS_PARAMS = {FOCUS_PARAMS}")

# %% [markdown]
# ## 4. Per-parameter mean-net plots

# %% [markdown]
# ### 4a. Predictions overlaid across cases (per parameter)

# %%
for p in FOCUS_PARAMS:
    ctx.plots.plot_param_all_val(p, mode="aligned")
    relabel_figure(ctx)
    plt.show()

# %% [markdown]
# ### 4b. Dual-curve -- aligned + both shuffle modes with 10-perm +/-sigma bands

# %%
if ctx.r2_matrix_shifted_obs is not None and ctx.r2_matrix_shifted_both is not None:
    dual_r2_df = build_dual_r2_df(ctx)
    for p in FOCUS_PARAMS:
        try:
            ctx.plots.plot_param_curve_dual(dual_r2_df, p, figsize=(8, 5), show_band=True)
            relabel_figure(ctx)
            plt.show()
        except Exception as e:
            print(f"[warn] {p}: {e}")

# %% [markdown]
# ### 4c. Prediction attractor map
# One panel per param: every noise case becomes a binned mean(pred) vs true
# curve, so you see how the pred/truth relationship shifts across the case
# sequence in one view. y=x = perfect info; y=mean(true) = no info (collapsed
# to the prior mean). The both-clean reference case is drawn bold black.

# %%
for p in FOCUS_PARAMS:
    try:
        fig, stats = ctx.plots.plot_prediction_attractor_map(param=p)
        relabel_figure(ctx)
        plt.show()
    except Exception as e:
        print(f"[warn] plot_prediction_attractor_map({p}): {e}")

# %% [markdown]
# ### 4d. Unordered-pair normalized values
# Like 4e below, but pairs are sampled (not aligned val rows) and normalized
# by P_norm = (pred - t0)/(t1 - t0) for each unordered sim pair (i,j).

# %%
for p in FOCUS_PARAMS:
    try:
        fig, stats = ctx.plots.plot_param_unordered_pair_normalized_values(
            param=p, space="processed", min_abs_denom=1.5,
        )
        relabel_figure(ctx)
        plt.show()
    except Exception as e:
        print(f"[warn] plot_param_unordered_pair_normalized_values({p}): {e}")

# %% [markdown]
# ### 4e. Pair-normalized values -- one param, one mode

# %%
PAIR_PARAM = FOCUS_PARAMS[0] if FOCUS_PARAMS else "θ4"
try:
    ctx.plots.plot_param_pair_normalized_values(
        PAIR_PARAM, space="processed",
        mode="obs2_vs_truth",
        normalize_endpoints="obs1_to_obs2",
    )
    relabel_figure(ctx)
    plt.show()
except Exception as e:
    print(f"[warn] plot_param_pair_normalized_values({PAIR_PARAM}): {e}")

# %% [markdown]
# ### 4f. Side-by-side pair-normalized shuffle scatter

# %%
def side_by_side_shuffle_scatter(param):
    fig, axes = plt.subplots(1, 2, figsize=(15, 7.5))
    _ax_iter = iter(axes)
    _orig = plt.subplots
    plt.subplots = lambda *a, **k: (fig, next(_ax_iter))
    try:
        ctx.plots.plot_pair_normalized_shuffle_scatter(
            param=param, n_pairs="all", case=None,
            mode="obs1_vs_truth", color_by_theta_diff=True)
        ctx.plots.plot_pair_normalized_shuffle_scatter(
            param=param, n_pairs="all", case=None,
            mode="obs2_vs_truth", color_by_theta_diff=True)
    finally:
        plt.subplots = _orig
    fig.tight_layout()
    return fig

for p in FOCUS_PARAMS:
    try:
        fig = side_by_side_shuffle_scatter(p)
        relabel_figure(ctx, fig)
        plt.show()
    except Exception as e:
        print(f"[warn] shuffle_scatter({p}): {e}")

# %% [markdown]
# ### 4g. Pair-truth scatter -- prediction vs anchor truth, all unique sim pairs, both observables
# For every unique pair of validation sims (i, j), x = the anchor sim's
# truth, y = the chimera prediction, colored by the SIGNED
# truth_partner - truth_anchor (not the absolute value). Two panels per
# param: anchor_obs="obs1" (anchor keeps obs1, partner swaps in obs2) and
# anchor_obs="obs2" (anchor keeps obs2, partner swaps in obs1) -- so each
# parameter gets both directions. Aligned (own-data) points -- the model's
# own prediction -- are marked with a plus. y = x means the prediction
# landed exactly on the anchor's truth.

# %%
def side_by_side_pair_truth_scatter(param):
    fig, axes = plt.subplots(1, 2, figsize=(15, 7.0))
    _ax_iter = iter(axes)
    _orig = plt.subplots
    plt.subplots = lambda *a, **k: (fig, next(_ax_iter))
    try:
        ctx.plots.plot_param_pair_truth_scatter(param, anchor_obs="obs1", n_pairs="all")
        ctx.plots.plot_param_pair_truth_scatter(param, anchor_obs="obs2", n_pairs="all")
    finally:
        plt.subplots = _orig
    fig.tight_layout()
    return fig

for p in FOCUS_PARAMS:
    try:
        fig = side_by_side_pair_truth_scatter(p)
        relabel_figure(ctx, fig)
        plt.show()
    except Exception as e:
        print(f"[warn] pair_truth_scatter({p}): {e}")

# %% [markdown]
# ### 4h. Consolidated per-parameter summary
# Puts the four views above (4b dual R2-vs-noise curve, 4c attractor map,
# 4f shuffle scatter, 4g pair-truth scatter -- 6 axes total, since 4f/4g are
# each 2 panels) into one combined figure per FOCUS_PARAM, by reusing the
# exact same plot calls and just redirecting each one's own plt.subplots()
# onto the next slot of a shared grid, same trick as side_by_side_* above.

# %%
def consolidated_param_summary(param):
    fig, axes = plt.subplots(3, 2, figsize=(15, 18))
    _ax_iter = iter(axes.flat)
    _orig_subplots = plt.subplots
    _orig_show = plt.show
    # plot_param_curve_dual calls plt.show() internally, which under
    # Jupyter's inline backend (close_figures=True by default) would
    # prematurely display/close this shared fig after only 1/6 panels are
    # filled. No-op plt.show() during the inner calls; call the real one
    # once at the end via relabel_figure/plt.show() in the caller below.
    plt.subplots = lambda *a, **k: (fig, next(_ax_iter))
    plt.show = lambda *a, **k: None
    try:
        ctx.plots.plot_param_curve_dual(dual_r2_df, param, show_band=True)
        ctx.plots.plot_prediction_attractor_map(param=param)
        ctx.plots.plot_pair_normalized_shuffle_scatter(
            param=param, n_pairs="all", case=None,
            mode="obs1_vs_truth", color_by_theta_diff=True)
        ctx.plots.plot_pair_normalized_shuffle_scatter(
            param=param, n_pairs="all", case=None,
            mode="obs2_vs_truth", color_by_theta_diff=True)
        ctx.plots.plot_param_pair_truth_scatter(param, anchor_obs="obs1", n_pairs="all")
        ctx.plots.plot_param_pair_truth_scatter(param, anchor_obs="obs2", n_pairs="all")
    finally:
        plt.subplots = _orig_subplots
        plt.show = _orig_show
    fig.suptitle(f"{param} -- consolidated summary", fontsize=13, y=1.005)
    fig.tight_layout()
    return fig

for p in FOCUS_PARAMS:
    try:
        fig = consolidated_param_summary(p)
        relabel_figure(ctx, fig)
        plt.show()
    except Exception as e:
        print(f"[warn] consolidated_param_summary({p}): {e}")

# %% [markdown]
# ## 5. Moment-network summary plots
# Only render if this pair has a moment head.

# %%
has_moment = getattr(ctx, "has_moment", False) or ctx.has_variance
if not has_moment:
    print("This pair has no moment_model -- section 5 will no-op.")

# %% [markdown]
# ### 5a. Predicted mu +/- sigma vs true, per param
# One panel per case per param. Points inside error bars = well-calibrated.
# `pull std = X.XX` printed on each panel -- 1.0 is perfect calibration.

# %%
if has_moment:
    for p in FOCUS_PARAMS:
        try:
            ctx.plots.plot_predictions_with_errorbars(p, cases=ctx.cases, space="log_partial")
            relabel_figure(ctx)
            plt.show()
        except Exception as e:
            print(f"[warn] {p}: {e}")

# %% [markdown]
# ### 5b. Population sigma per case per param -- bar chart

# %%
if has_moment:
    ctx.plots.plot_sigma_by_case_bars(FOCUS_PARAMS, ctx.cases,
                                       space="log_partial", reducer="median")
    relabel_figure(ctx)
    plt.show()

# %% [markdown]
# ### 5c. Calibration -- pull distribution per case

# %%
if has_moment:
    ctx.plots.plot_pull_distribution(ctx.cases, space="normalized", params=FOCUS_PARAMS)
    plt.show()

# %% [markdown]
# ### 5d. Median correlation matrix per case

# %%
if has_moment:
    ctx.plots.plot_median_correlation_grid(ctx.cases, space="log_partial")
    plt.show()

# %% [markdown]
# ### 5e. Corner plot -- all cases overlaid, one representative sim

# %%
if has_moment:
    CORNER_SIM_IDX = 0
    ctx.plots.plot_corner(sim_idx=CORNER_SIM_IDX, cases=ctx.cases, space="log_partial")
    relabel_figure(ctx)
    plt.show()

# %% [markdown]
# ### 5f. Prediction scatter corner -- one per case

# %%
if has_moment:
    for c in ctx.cases:
        try:
            ctx.plots.plot_prediction_scatter_corner(c, space="log_partial")
            plt.show()
        except Exception as e:
            print(f"[warn] scatter_corner({c}): {e}")

# %% [markdown]
# ## 6. Save the last figure
# Explicit path so you can drop plots into your notes.

# %%
SAVE_DIR = os.path.join(ctx.results_dir, "plots", "notebook")
os.makedirs(SAVE_DIR, exist_ok=True)
save_name = "custom_plot.png"
plt.gcf().savefig(os.path.join(SAVE_DIR, save_name), dpi=150, bbox_inches="tight")
print(f"saved {os.path.join(SAVE_DIR, save_name)}")

# %% [markdown]
# ## 7. Scratch -- anything else you want to try
# Every plot function from src/plots.py is available as `ctx.plots.<name>`.
# Every pipeline helper as `ctx.pipeline.<name>`. Tab-complete in Jupyter.

# %%
if ctx.has_variance:
    SIM = 0
    print(f"Sim #{SIM}  -- mu +/- sigma  (log_partial space)")
    for cidx, r in enumerate(ctx.all_results):
        mu, sigma, truth = ctx.pipeline.predict_with_uncertainty(r, space="log_partial")
        print(f"\n  case = {ctx.display_names[r['case_name']]}")
        for p in FOCUS_PARAMS:
            pidx = ctx.param_names.index(p)
            print(f"    {p:5s}  mu={mu[SIM,pidx]:+.3f}  sigma={sigma[SIM,pidx]:.3f}  true={truth[SIM,pidx]:+.3f}"
                  f"   pull={(mu[SIM,pidx]-truth[SIM,pidx])/sigma[SIM,pidx]:+.2f}")
